# Generated by Django 3.2.7 on 2021-12-10 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comedian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='芸名')),
                ('is_solo', models.BooleanField(default=False, verbose_name='ピン芸人')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '芸人（個人）',
                'verbose_name_plural': '芸人（個人）',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='会社名')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '会社',
                'verbose_name_plural': '会社',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='グループ名')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'グループ',
                'verbose_name_plural': 'グループ',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='タグ名')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
            },
        ),
        migrations.CreateModel(
            name='GroupTagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comedians.group', verbose_name='グループ')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comedians.tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': 'グループのタグ紐付け',
                'verbose_name_plural': 'グループのタグ紐付け',
                'unique_together': {('group', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='group_tags', through='comedians.GroupTagGroup', to='comedians.Tag', verbose_name='タグ一覧'),
        ),
        migrations.CreateModel(
            name='ComedianTagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('comedian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comedians.comedian', verbose_name='芸人')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='comedians.tag', verbose_name='タグ')),
            ],
            options={
                'verbose_name': '芸人のタグ紐付け',
                'verbose_name_plural': '芸人のタグ紐付け',
                'unique_together': {('comedian', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='comedian',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comedians.company', verbose_name='会社'),
        ),
        migrations.AddField(
            model_name='comedian',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comedians.group', verbose_name='グループ'),
        ),
        migrations.AddField(
            model_name='comedian',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='comedian_tags', through='comedians.ComedianTagGroup', to='comedians.Tag', verbose_name='タグ一覧'),
        ),
    ]
